### ISSUE TITLE
iPat Error using BGLR: "Error in file(description = fname, open = "w") :    cannot open the connection"

### ISSUE THREAD

**Issue by jcrsoy** [Poissonfish/iPat#7]
Error in file(description = fname, open = "w") : 
  cannot open the connection
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
In addition: Warning messages:
1: package 'BGLR' was built under R version 3.5.2 
2: package 'rrBLUP' was built under R version 3.5.2 
3: package 'data.table' was built under R version 3.5.2 
4: package 'magrittr' was built under R version 3.5.2 
5: package 'ggplot2' was built under R version 3.5.2 
6: In doTryCatch(return(expr), name, parentenv, handler) :
  NAs introduced by coercion
7: In file(description = fname, open = "w") :
  cannot open file 'iPat_Project_BGLR_ETA_1_varB.dat': Permission denied
Execution halted

**Comment by Poissonfish** [comment]
Sorry for the late reply. Would you mind to provide your system information (like OS)? Did you have the file "iPat_Project_BGLR_ETA_1_varB.dat" opened while you run iPat?

**Comment by jcrsoy** [comment]
windows 7 is the operating system, i did not open the "iPat_Project_BGLR_ETA_1_varB.dat" is there some more detailed instruction or examples on using the rrBLUP and BGLR in iPat?

**Comment by Poissonfish** [comment]
Thank for your update. You can follow the instruction in http://poissonfish.github.io/iPat/k-fold-cross-validation-gs-in-bglr.html for the usage of BGLR module. And if you don’t mind, would you like to share your data with me.so that I can have a better information for you question? Thank you.

James Chen, Ph.D. Candidate
107 Johnson Hall, Zhang Lab
Dept. Crop and Soil Sciences, Washington State University
Pullman WA, 99164, USA




On Mar 18, 2019, at 2:11 PM, jcrsoy <notifications@github.com<mailto:notifications@github.com>> wrote:


windows 7 is the operating system, i did not open the "iPat_Project_BGLR_ETA_1_varB.dat" is there some more detailed instruction or examples on using the rrBLUP and BGLR in iPat?

**Comment by jcrsoy** [comment]
I tried a different PC with windows 10 and did not get the error, this may be something related to windows 7. Thanks for the help
