### ISSUE TITLE
GS on 

### ISSUE THREAD

**Issue by JRTuck** [Poissonfish/iPat#8]
Dear James,

I hope you can give guidance on genomic selection application.

I have a Genome wide association population (Genotype & Phenotype) that was used to develop a predictive model.  I wish to you this to make GEBV prediction in F6 bi-parental breeding populations based on genotype values.  Could you kindly detail how data should be inputted into iPat so I can define the GWAS population as the training set to calculate the GEBV in these new F6 populations to ultimately apply selection selection on them.  ie. I wish to use the GWAS population to define marker effects and apply these to the non-phenotyped F6s to select them based on GEBV.

thank you kindly,

James

**Comment by Poissonfish** [comment]
Hi James,

Thanks for your question.

GWAS-defined effects would lead to bias in a GS model. Since GWAS only considers one marker at a time, whereas GS assumes all the markers would jointly contribute linear variation toward the trait of interest. Two alternative strategies can also accomplish what you mentioned in the question: (1) performing GS and estimating GEBV directly (see tutorial [here](http://poissonfish.github.io/iPat/k-fold-cross-validation-gs-in-bglr.html)). Or, (2) do GWAS-assisted GS if you believe some of your markers play a critical role in your scheme (see tutorial [here](http://poissonfish.github.io/iPat/gwas-assisted-gs-in-rrblup.html)). It's noted that for your problem, you want to have the option "[Validation on accuracy](http://poissonfish.github.io/iPat/gs.html)" UNCHECKED since you only want to estimate the GEBV instead of validating the markers.

For the data format, please follow the GS section in the [user manual](http://poissonfish.github.io/iPat/gs.html). You can download the demo files from [here](http://zzlab.net/iPat/demo.zip), too.

To tell iPat which individuals are required to be estimated for GEBV, you can simply leave their phenotypic values as "NA" and the program would take the other part of data as a training set.

Hope the above answer your question well.

Sincerely,
James

**Comment by JRTuck** [comment]
Thanks for response on 'NA' … I will give it a try.

James
